src/Entity/Messages.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\Trait\CreatedAtTrait;
use App\Repository\MessagesRepository;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    use CreatedAtTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'sender')]
    #[ORM\JoinColumn(nullable: false)]
    private $sender;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'recipient')]
    #[ORM\JoinColumn(nullable: false)]
    private $recipient;

    #[ORM\Column(type: 'text')]
    private $message;

    #[ORM\Column(type: 'string', length: 20)]
    private $title;

    #[ORM\Column(type: 'boolean')]
    private$isread = 0 ;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;
    public function __construct()
    {
        
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function isIsread(): ?bool
    {
        return $this->isread;
    }

    public function setIsread(bool $isread): self
    {
        $this->isread = $isread;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Objet.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ObjetRepository;
use App\Entity\Trait\CreatedAtTrait;

#[ORM\Entity(repositoryClass: ObjetRepository::class)]
class Objet
{
    use CreatedAtTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'boolean')]
    private $status;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\Column(type: 'string', length: 255)]
    private $lost_adress;

    #[ORM\Column(type: 'string', length: 5)]
    private $lost_zip;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'objets')]
    #[ORM\JoinColumn(nullable: false)]
    private $User;




    #[ORM\Column(type: 'boolean')]
    private $active;

    #[ORM\Column(type: 'boolean')]
    private $isfound;

    #[ORM\Column(type: 'string', length: 255)]
    private $clues;

    #[ORM\ManyToOne(targetEntity: Categories::class, inversedBy: 'objets')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\ManyToOne(targetEntity: CategoriesDetails::class, inversedBy: 'objets')]
    private $categoryDetails;

    #[ORM\Column(type: 'date', nullable: true)]
    private $LostDate;

    #[ORM\Column(type: 'string', length: 25, nullable: true)]
    private $lostCity;

    
    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        if (!is_null($image)) {
            $this->image = $image;
        }
        return $this;

        return $this;
    }

    public function getLostAdress(): ?string
    {
        return $this->lost_adress;
    }

    public function setLostAdress(string $lost_adress): self
    {
        $this->lost_adress = $lost_adress;

        return $this;
    }

    public function getLostZip(): ?string
    {
        return $this->lost_zip;
    }

    public function setLostZip(string $lost_zip): self
    {
        $this->lost_zip = $lost_zip;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function isIsfound(): ?bool
    {
        return $this->isfound;
    }

    public function setIsfound(bool $isfound): self
    {
        $this->isfound = $isfound;

        return $this;
    }

    public function getClues(): ?string
    {
        return $this->clues;
    }

    public function setClues(string $clues): self
    {
        $this->clues = $clues;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCategoryDetails(): ?CategoriesDetails
    {
        return $this->categoryDetails;
    }

    public function setCategoryDetails(?CategoriesDetails $categoryDetails): self
    {
        $this->categoryDetails = $categoryDetails;

        return $this;
    }

    public function getLostDate(): ?\DateTimeInterface
    {
        return $this->LostDate;
    }

    public function setLostDate(?\DateTimeInterface $LostDate): self
    {
        $this->LostDate = $LostDate;

        return $this;
    }

    public function getLostCity(): ?string
    {
        return $this->lostCity;
    }

    public function setLostCity(?string $lostCity): self
    {
        $this->lostCity = $lostCity;

        return $this;
    }
    public function __toString()
    {
        return $this->id;
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Repository\MessagesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


#[
    Route('/message'),

    IsGranted("ROLE_USER"),
]


class MessagesController extends AbstractController
{
    #[Route('/messagesreçus', name: 'app_messages_recu', methods: ['GET'])]
    public function indexrecu(MessagesRepository $messagesRepository): Response
    {
        return $this->render('messages/messageRecu.html.twig', [
            'messages' => $messagesRepository->findby(
                array(),
                array('created_at' => 'ASC')
            ),
        ]);
    }

    #[Route('/messagesenvoyes', name: 'app_messages_envoyes', methods: ['GET'])]
    public function indexenvoi(MessagesRepository $messagesRepository): Response
    {

        return $this->render('messages/messageEnvo.html.twig', [
            'messages' => $messagesRepository->findby(
                array(),
                array('title' => 'ASC')
            ),
        ]);
    }
    #[Route('/new', name: 'app_messages_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MessagesRepository $messagesRepository): Response
    {  
        $message = new Messages();
        $form = $this->createForm(MessagesType::class, $message);
        $messageData =  $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash('success', 'Votre message a etait bien envoye');
            $message->setSender($this->getUser());
            $messagesRepository->add($message);
            return $this->redirectToRoute('app_messages', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('messages/new.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_messages_show', methods: ['GET'])]
    public function show(Messages $message,   EntityManagerInterface $entityManager): Response
    {
        $message->setisread(true);

        $entityManager->persist($message);
        $entityManager->flush();
        return $this->render('messages/show.html.twig', [
            'message' => $message,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_messages_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Messages $message, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MessagesType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($message);
            $entityManager->flush();
            return $this->redirectToRoute('app_messages_recu', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('messages/edit.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_messages_delete', methods: ['POST'])]
    public function delete(Request $request, Messages $message,  EntityManagerInterface $entityManager): Response
    {

        if ($this->isCsrfTokenValid('delete' . $message->getId(), $request->request->get('_token'))) {
            $entityManager->remove($message);
            $entityManager->flush();
        }
        if ($message->getSender()->getId() == $this->getUser()->getId()) {
            return  $this->redirectToRoute('app_messages_envoyes', [], Response::HTTP_SEE_OTHER);
        }else {
            return  $this->redirectToRoute('app_messages_recu', [], Response::HTTP_SEE_OTHER);
        }
    }
}

templates/messages/_delete_form.html.twig
<form method="post" action="{{ path('app_messages_delete', {'id': message.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer ce message ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn text-danger"><span class="fa fa-trash-o fa-lg" aria-hidden="true"></span></button>
</form>

templates/messages/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/messages/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Messages{% endblock %}

{% block body %}
    <h1>Edit Messages</h1>

    {{ include('messages/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="">back to list</a>

    {{ include('messages/_delete_form.html.twig') }}
{% endblock %}

templates/messages/messageEnvo.html.twig
{% extends 'base2.html.twig' %}


{% block title %}Messages envoyees
{% endblock %}

{% block body %}
	<section>
		<div class="container py-5">
			{% if  app.user.sender | length  == 0 %}
				<h1 class="text-center m-5 p-5">
					<span>
						<i class="fa-solid fa-message-slash"></i>
					</span>
					vous n'avez pas de message encore
				</h1>
			{% else %}
				<h3 class="m-3">
					vous avez
					{{ app.user.sender | length }}
					Messages envoyes
				</h3>
				<table class="table bg-white h-75 m-5">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">a</th>
							<th scope="col">sujet</th>
							<th scope="col">images</th>
							<th scope="col">date</th>
							<th scope="col">action</th>
						</tr>
					</thead>
					<tbody>
						{% set id = 0 %}
						{% set n = 0 %}
						{% for message in app.user.sender |sort ((a, b) => b.id <=> a.id) %}
							{% set n = n + 1 %}
							<tr>
								<th scope="row"></th>
								<td>{{ message.recipient.firstname }}
								</td>
								<td>
									<h6>{{ message.title }}</h6>
									<div class="collapse" id="collapseExample{{n}}">
										<div class="card card-body">
											{{ message.message }}
										</div>
									</div>
								</td>
								{% if message.image == null %}
									{% set id = id + 1 %}
									<td>
										<span class="fa fa-file-image-o"></span>
									</td>
								{% else %}
									<td>
										<a href="{{ asset('uploads/messages/'~ message.image) }}" target="_blank"><img style="width: 20px;" src="{{ asset('uploads/messages/'~ message.image) }}" alt="..."/></a>
									</td>
								{% endif %}
								<td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i') : '' }}</td>
								<td class="p-1">
									<div class="row">
										<button class="border-0  btn col-md-3 text-primary" data-bs-toggle="collapse" data-bs-target="#collapseExample{{n}}" aria-expanded="false" aria-controls="collapseExample">
											<span class="fa fa-eye" aria-hidden="true"></span>
										</button>
										<div class="col-md-3 border-0 ">{{ include('messages/_delete_form.html.twig') }}</div>
									</div>
								</td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
			</table>

			
		</div>
		{% include "partials/footer.html.twig" %}
	</section>
{% endblock %}

templates/messages/messageRecu.html.twig
{% extends 'base2.html.twig' %}


{% block title %}messages reçus
{% endblock %}

{% block body %}
<section>
	<div class="container py-5">
		{% if  app.user.recipient | length  == 0 %}
			<h1 class="text-center m-5 p-5">
				<span>
					<i class="fa-solid fa-message-slash"></i>
				</span>
				vous n'avez pas de message encore
			</h1>
		{% else %}

			<h3 class="m-3">
				vous avez
				{{ app.user.recipient | length }}
				messages reçus
			</h3>


			<table class="table bg-white h-75 m-5">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">de</th>
						<th scope="col">sujet</th>
						<th scope="col">image</th>
						<th scope="col">date</th>
						<th scope="col">action</th>
					</tr>
				</thead>
				<tbody>
					{% for message in app.user.recipient |sort ((a, b) => b.id <=> a.id) %}

						{% if message.isread == 0  %}
							{% set blod = "fw-bold thead-light" %}
						{% else %}
							{% set blod = "" %}
						{% endif %}

						<tr class={{blod}}>
							<th scope="row ">1</th>
							<td>
								{{ message.sender.firstname }}
							</td>
							<td>{{ message.title }}</td>
							{% if message.image == null %}
								<td>
									<span class="fa fa-file-image-o"></span>
								</td>
							{% else %}
								<td><img style="width: 20px;" src="{{ asset('uploads/messages/'~ message.image) }}" alt="..."/></td>
							{% endif %}
							<td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i:s') : '' }}</td>
							<td class="p-1">
								<div class="row">
									<a class=" btn col-md-3 text-primary" href="{{ path('app_messages_show', {'id': message.id}) }}">
										<span class="fa fa-eye" aria-hidden="true"></span>
									</a>
									<div class="col-md-3 ">{{ include('messages/_delete_form.html.twig') }}</div>

								</div>
							</td>

						</tr>

					{% endfor %}
				</tbody>
			</table>
		{% endif %}
	
	</div>
</section>
	{% include "partials/footer.html.twig" %}
{% endblock %}

templates/messages/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}nouveau message{% endblock %}

{% block body %}
    <h1>Créer un nouveau message</h1>

    {{ include('messages/_form.html.twig') }}

    <a href="{{ path('app_messages') }}">retour à la liste</a>
{% endblock %}

templates/messages/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Messages
{% endblock %}

{% block body %}
	<div class="col-md-8">
		<h1>Messages</h1>

		<table class="table">
			<tbody>
	<tr>
					<th>title</th>
					<td>{{ message.title }}</td>
				</tr>

				<tr>
					<th>Message</th>
					<td>{{ message.message }}</td>
				</tr>

			

				{% if message.image == null %}
					{% else %}
						<tr>
							<th>image</th>
							<td><a href="{{ asset('uploads/messages/'~ message.image) }}"><img style="width: 90px;" src="{{ asset('uploads/messages/'~ message.image) }}" alt="..."/></a></td>
						</tr>
				{% endif %}
					<td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i:s') : '' }}</td>

			</tbody>
		</table>


		<div class="row">
			<a class=" btn col-md-3 text-primary" href="{{ path('app_messages_recu', {'id': message.id}) }}">
				<i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i>
			</a>
			<div class="col-md-3 ">{{ include('messages/_delete_form.html.twig') }}</div>

		</div>
	</div>
{% endblock %}